fix: wrong property names "ingerssHost" modify to "ingressHost"
FederatedAI/KubeFATE pull request #615
Opened 2022-05-17 09:54 UTC by magic-hya

Fix  wrong property names "ingerssHost" modify to "ingressHost" in values-template.yaml

When I used version 1.7.0, I found this problem. Now 1.9.0 still exists. So I submit this fix

2022-05-17 11:32 UTC, JingChen23 requested changes
Hi @magic-hya , thanks for the fix! Two things:
1. I just checked the helm chart, there is no place using this variable. So let's remove it. But still thank you for finding the typo.
2. You need to raise a PR to the branch `develop-1.9.0`. `master` cannot be changed now. When 1.9.0 is released, everything will be merged to master in one big PR.

2022-05-17 11:32 UTC, JingChen23 commented on helm-charts/FATE-Serving/values-template.yaml
> +  ingressHost: {{ .ingressHost | default (printf "%s.serving-admin.example.com" $partyId) }}
Instead of changing this, you can remove this.

2022-05-17 11:33 UTC, JingChen23 commented
Also, please follow the `Details` to resolve your DOC issue.

2022-05-18 12:28 UTC, magic-hya commented
I've tried to modify it, but there are more mistakes. I'll open a new PR tomorrow，thank！

2022-05-18 12:29 UTC, closed without merging