Fix issue 719
FederatedAI/KubeFATE pull request #731
Opened 2022-08-23 13:30 UTC by n063h

Fixes  ISSUE#xxx

Changes:

1. allow users to customize pulsar env
2. fix sslPort format error

Before
```
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - bin/pulsar standalone -nss
    image: federatedai/pulsar:2.7.0
```

After
User can customize pulsar env in yaml, like
```
  env:
  - name: PULSAR_MEM
    value: "-Xms4g -Xmx4g -XX:MaxDirectMemorySize=8g"
```
then run `❯ k edit pod -n fate-10000 pulsar-0`, you can see
```
    env:
    - name: PULSAR_MEM
      value: -Xms4g -Xmx4g -XX:MaxDirectMemorySize=8g
    image: federatedai/pulsar:2.7.0
    imagePullPolicy: IfNotPresent
```
and run `❯ kexn  fate-10000 -it  pulsar-0 bash`, you can see
```
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@pulsar-0:/pulsar# echo $PULSAR_MEM
-Xms4g -Xmx4g -XX:MaxDirectMemorySize=8g
```
It turns out the env has been set inside container.

2022-08-24 01:41 UTC, JingChen23 commented
There should be another 2 configurations?

https://github.com/FederatedAI/KubeFATE/pull/715/files

We also need to varibalize the 2 configurations in pulsar's configmap, make them in the cluster.yaml

2022-08-24 18:19 UTC, n063h commented
> There should be another 2 configurations?
> 
> https://github.com/FederatedAI/KubeFATE/pull/715/files
> 
> We also need to varibalize the 2 configurations in pulsar's configmap, make them in the cluster.yaml

It's done.

2022-08-25 12:07 UTC, JingChen23 requested changes
Overall looks good, just need to help change another doc, thanks!

2022-08-25 12:07 UTC, JingChen23 commented on k8s-deploy/examples/party-10000/cluster-spark-local-pulsar.yaml
> +  confs:
In examples, we don't write useless stuffs. I suggest remove them and update the document:

https://github.com/FederatedAI/KubeFATE/blob/develop-1.9.0/docs/configurations/FATE_cluster_configuration.md

I find that this document has no configration information for pulsar. So please help to add all the pulsar related information into this file, thank you very much!!

2022-08-25 12:07 UTC, JingChen23 commented on k8s-deploy/examples/party-10000/cluster-spark-pulsar.yaml
> +  confs:
ditto.

2022-08-25 12:07 UTC, JingChen23 commented on k8s-deploy/examples/party-9999/cluster-spark-local-pulsar.yaml
> +  confs:
ditto

2022-08-25 12:07 UTC, JingChen23 commented on k8s-deploy/cluster-spark-pulsar.yaml
> +  # env:
Add `conf:` below this line?

2022-08-29 03:05 UTC, JingChen23 approved these changes

2022-08-30 02:07 UTC, merged